{
	"version": 1726109015,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbg.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/tiledjalan.png",
		"images/hjalan-sheet0.png",
		"images/hright-sheet0.png",
		"images/truck-sheet0.png",
		"images/enemy-sheet0.png",
		"images/sampah-sheet0.png",
		"images/sampah-sheet1.png",
		"images/bg-sheet0.png",
		"images/awan.png",
		"images/rintangan-sheet0.png",
		"images/gameover-sheet0.png",
		"images/bgmenu-sheet0.png",
		"images/logo-sheet0.png",
		"images/btnmulai-sheet0.png",
		"images/btnhelp-sheet0.png",
		"images/btnhelp-sheet1.png",
		"images/btnsetting-sheet0.png",
		"images/btnsetting-sheet1.png",
		"images/story1-sheet0.png",
		"images/story2-sheet0.png",
		"images/petunjuk-sheet0.png",
		"images/btnclose-sheet0.png",
		"images/btnclose-sheet1.png",
		"images/pengaturan-sheet0.png",
		"images/btnreplay-sheet0.png",
		"images/btnreplay-sheet1.png",
		"images/btnhome-sheet0.png",
		"images/btnhome-sheet1.png",
		"images/gamewin-sheet0.png",
		"images/story3-sheet0.png",
		"images/soundmute-sheet0.png",
		"images/snd-sheet0.png",
		"images/black-sheet0.png",
		"images/mute-sheet0.png",
		"images/labelspace-sheet0.png",
		"images/btnidea-sheet0.png",
		"images/idea-sheet0.png",
		"media/menu klik.m4a",
		"media/menu klik.ogg",
		"media/truk.m4a",
		"media/truk.ogg",
		"media/backsound menu.m4a",
		"media/backsound menu.ogg",
		"media/pas main.m4a",
		"media/pas main.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/faint.m4a",
		"media/faint.ogg",
		"media/victory.m4a",
		"media/victory.ogg",
		"media/backsound story.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}